import { Effect, Console } from "effect"
import type { ValidationResult, GitHubIssueData } from "../types"
import { exec } from "node:child_process"
import { promisify } from "node:util"

const execAsync = promisify(exec)

/**
 * Creates a GitHub issue for validation failures
 */
export const createIssue = (
  results: ValidationResult[],
): Effect.Effect<void, Error> =>
  Effect.gen(function* () {
    const failedResults = results.filter((r) => !r.passed)

    if (failedResults.length === 0) {
      yield* Console.log("✓ All documentation up to date")
      return
    }

    const issueData = formatIssue(failedResults)

    // Use gh CLI to create issue
    const command = [
      "gh",
      "issue",
      "create",
      "--title",
      JSON.stringify(issueData.title),
      "--body",
      JSON.stringify(issueData.body),
      "--label",
      "documentation,automated",
    ].join(" ")

    yield* Effect.tryPromise({
      try: async () => {
        const { stdout, stderr } = await execAsync(command)
        if (stderr) console.error("gh stderr:", stderr)
        return stdout
      },
      catch: (error) => new Error(`Failed to create GitHub issue: ${error}`),
    })

    yield* Console.log("✓ Created GitHub issue for doc drift")
  })

/**
 * Formats validation results into GitHub issue
 */
const formatIssue = (failedResults: ValidationResult[]): GitHubIssueData => {
  const title = `Documentation Drift Detected: ${failedResults.length} file${failedResults.length > 1 ? "s" : ""} outdated`

  const body = `## Automated Documentation Validation Report

**Generated:** ${new Date().toISOString()}

The following documentation files have discrepancies with their source repositories:

${failedResults
  .map((result) => {
    return `### ${result.targetName}

**Status:** ❌ Failed

**Discrepancies:**
${result.discrepancies
  .map((d) => {
    return `- **[${d.severity.toUpperCase()}]** ${d.section}
  - Issue: ${d.issue}${d.suggestedFix ? `\n  - Suggested Fix: ${d.suggestedFix}` : ""}`
  })
  .join("\n")}

---
`
  })
  .join("\n")}

## Next Steps

1. Review the discrepancies above
2. Update local documentation to match source repositories
3. Verify changes maintain best practices
4. Close this issue once resolved

---
*This issue was automatically generated by the doc-validator*`

  return {
    title,
    body,
    labels: ["documentation", "automated"],
  }
}

/**
 * Alternative: Create a PR with fixes (requires Claude Agent SDK)
 */
export const createPullRequest = (
  results: ValidationResult[],
): Effect.Effect<void, Error> =>
  Effect.gen(function* () {
    // TODO: Implement PR creation with automated fixes
    // Would use Agent SDK to generate updated docs based on source
    yield* Console.log("PR creation not yet implemented")
    return yield* Effect.fail(new Error("Not implemented"))
  })
