// Auto-generated by scripts/update-reference-manifest.mjs
import SKILL_DOCUMENT_RAW from "../../../SKILL.md" with { type: "text" };
import REF__00_index_md from "../../website/references/00-index.md" with { type: "text" };
import REF__01_repo_setup_md from "../../website/references/01-repo-setup.md" with { type: "text" };
import REF__02_tsconfig_md from "../../website/references/02-tsconfig.md" with { type: "text" };
import REF__03_services_and_layers_md from "../../website/references/03-services-and-layers.md" with { type: "text" };
import REF__04_effect_style_md from "../../website/references/04-effect-style.md" with { type: "text" };
import REF__05_data_types_md from "../../website/references/05-data-types.md" with { type: "text" };
import REF__06_error_handling_md from "../../website/references/06-error-handling.md" with { type: "text" };
import REF__07_config_md from "../../website/references/07-config.md" with { type: "text" };

export const SKILL_DOCUMENT = SKILL_DOCUMENT_RAW;

export const REFERENCE_FILES = [
  "00-index.md",
  "01-repo-setup.md",
  "02-tsconfig.md",
  "03-services-and-layers.md",
  "04-effect-style.md",
  "05-data-types.md",
  "06-error-handling.md",
  "07-config.md"
] as const;

export type ReferenceFile = (typeof REFERENCE_FILES)[number];

export const REFERENCE_CONTENT: Record<ReferenceFile, string> = {
  "00-index.md": REF__00_index_md,
  "01-repo-setup.md": REF__01_repo_setup_md,
  "02-tsconfig.md": REF__02_tsconfig_md,
  "03-services-and-layers.md": REF__03_services_and_layers_md,
  "04-effect-style.md": REF__04_effect_style_md,
  "05-data-types.md": REF__05_data_types_md,
  "06-error-handling.md": REF__06_error_handling_md,
  "07-config.md": REF__07_config_md,
};
